all:Run

Run:
	@/usr/bin/env /usr/lib/jvm/java-18-openjdk-amd64/bin/java -XX:+ShowCodeDetailsInExceptionMessages -cp /home/tarik/.config/Code/User/workspaceStorage/0cd8a976a9770f22514b5ece50f81faf/redhat.java/jdt_ws/odev7_d092c155/bin main 